# Use postgres/example user/password credentials
version: '3.9'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB : "DBDaw"
    ports:
      - "5433:5432"


  web:
    ports:
      - "8443:8443"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/DBDaw"
      SPRING_DATASOURCE_PASSWORD: "1234"
      SPRING_JPA_HIBERNATE_DDL-AUTO: create-drop
    image: '5df74dd7624f'
    restart: always
    depends_on:
      - db