# Use postgres/example user/password credentials
version: '3.9'

services:
  db:
    image: postgres:14.2
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB : "DBDaw"
    ports:
      - "5433:5432"


  web:
    ports:
      - "8443:8443"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/DBDaw"
      SPRING_DATASOURCE_PASSWORD: "password"
      SPRING_JPA_HIBERNATE_DDL-AUTO: create-drop
    image: 'ed5f2b51eef2'
    restart:always
    depends_on:
      - db